title: "Keep it simple"
author: Le Duy Quang
email: contact@quangleduy.com
description: Keep it simple
baseurl: ""
url: "http://quangleduy.com"
permalink: /:title/
twitter_username: leduyquang86
github_username:  leduyquang86

paginate: 10
markdown: kramdown

kramdown:
  input: GFM
  #syntax_highlighter: rouge
